### ISSUE TITLE
Clarify how NRK designers can contribute

### ISSUE THREAD

**Issue by mariuslundgard** [nrkno/core-icons#4]
@eirikbacker I don't have access to the FontAwesome docs. Could you post it here?

**Comment by eirikbacker** [comment]
@mariuslundgard Since the contribution-guide of font awesome is behind paywall, I'll rather not post it here. I have tried making some guidelines on..
- Contributing: https://static.nrk.no/core-styleguide/latest/#contributing
- Getting stated: https://static.nrk.no/core-styleguide/latest/?icons
- Getting stated template: https://static.nrk.no/core-styleguide/latest/#start
- Install and committing: https://github.com/nrkno/core-icons/blob/master/README.md
I am a bit unsure what level to put information on, so please provide more context if you feel we are missing somethign :)

**Comment by eirikbacker** [comment]
I'll close this until there is any further comments on how to improve :)
